/**
 * Error Codes Enumeration
 * 
 * Centralized error codes for consistent error handling across the application.
 * These codes are used in error responses and logging.
 */

export const ERROR_CODES = {
  // Authentication Errors (401)
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_MISSING: 'TOKEN_MISSING',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // Authorization Errors (403)
  FORBIDDEN: 'FORBIDDEN',
  ROLE_REQUIRED: 'ROLE_REQUIRED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  
  // Validation Errors (400)
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_EMAIL: 'INVALID_EMAIL',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  INVALID_FORMAT: 'INVALID_FORMAT',
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_TYPE: 'INVALID_TYPE',
  
  // Resource Errors (404, 409)
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  
  // Rate Limiting (429)
  RATE_LIMITED: 'RATE_LIMITED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  
  // Server Errors (500, 503)
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  
  // General
  BAD_REQUEST: 'BAD_REQUEST',
  MALFORMED_TOKEN: 'MALFORMED_TOKEN'
};

/**
 * Get HTTP status code from error code
 * 
 * @param {string} errorCode - Error code from ERROR_CODES
 * @returns {number} HTTP status code
 */
export const getStatusCodeFromErrorCode = (errorCode) => {
  const statusMap = {
    // 400 Bad Request
    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.INVALID_EMAIL]: 400,
    [ERROR_CODES.WEAK_PASSWORD]: 400,
    [ERROR_CODES.INVALID_FORMAT]: 400,
    [ERROR_CODES.MISSING_FIELD]: 400,
    [ERROR_CODES.INVALID_TYPE]: 400,
    [ERROR_CODES.BAD_REQUEST]: 400,
    [ERROR_CODES.MALFORMED_TOKEN]: 400,
    
    // 401 Unauthorized
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.TOKEN_EXPIRED]: 401,
    [ERROR_CODES.TOKEN_INVALID]: 401,
    [ERROR_CODES.TOKEN_MISSING]: 401,
    [ERROR_CODES.INVALID_CREDENTIALS]: 401,
    
    // 403 Forbidden
    [ERROR_CODES.FORBIDDEN]: 403,
    [ERROR_CODES.ROLE_REQUIRED]: 403,
    [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
    
    // 404 Not Found
    [ERROR_CODES.NOT_FOUND]: 404,
    
    // 409 Conflict
    [ERROR_CODES.ALREADY_EXISTS]: 409,
    [ERROR_CODES.DUPLICATE_ENTRY]: 409,
    
    // 429 Too Many Requests
    [ERROR_CODES.RATE_LIMITED]: 429,
    [ERROR_CODES.ACCOUNT_LOCKED]: 429,
    [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
    
    // 500 Internal Server Error
    [ERROR_CODES.INTERNAL_ERROR]: 500,
    [ERROR_CODES.DATABASE_ERROR]: 500,
    
    // 503 Service Unavailable
    [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
    [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 503
  };
  
  return statusMap[errorCode] || 500;
};

export default ERROR_CODES;

